import Head from "next/head";
import dynamic from "next/dynamic";

export default function Home() {
  const PanoComponent = dynamic(() => import("../components/Pano"), {
		ssr: false,
	});

	return (
		<div>
			<Head>
				<title>3D</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<PanoComponent />
			</main>
		</div>
	);
}
